apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-source-simple-app
spec:
  project: default
  sources:
  - repoURL: https://github.com/myorg/myrepo
    path: examples/directory
  - repoURL: https://github.com/myorg/myrepo
    path: examples/kustomize
    kustomize:
      namePrefix: "multi-"
      commonLabels:
        app: "multi-source-demo"
  destination:
    server: https://kubernetes.default.svc
    namespace: default