apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   name: multi-source-app
spec:
  project: default
  sources:
    - repoURL: https://github.com/myorg/myrepo
      path: examples/helm
      helm:
        parameters:
        - name: image.tag
          value: "1.21"
        - name: replicaCount
          value: "2"
    - repoURL: https://github.com/myorg/myrepo
      path: examples/kustomize
      kustomize:
        # Override the name prefix
        namePrefix: "staging-"

        # Override the name suffix
        nameSuffix: "-v2"

        # Override common labels
        commonLabels:
          environment: "staging"
          team: "platform"

        # Override common annotations
        commonAnnotations:
          app.kubernetes.io/version: "2.1.0"

        # Override images
        images:
        - "nginx:1.21"
        - "my-app:nginx:latest"

        # Override replica counts
        replicas:
        - name: my-app
          count: 5

        # Add patches
        patches:
        - target:
            kind: Deployment
            name: my-app
          patch: |-
            - op: add
              path: /spec/template/spec/containers/0/env
              value:
              - name: ENVIRONMENT
                value: "staging"

        # Add strategic merge patches
        patchesStrategicMerge:
        - |-
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: my-app
          spec:
            template:
              spec:
                containers:
                - name: my-app
                  resources:
                    requests:
                      memory: "128Mi"
                      cpu: "100m"
                    limits:
                      memory: "256Mi"
                      cpu: "200m"

  destination:
    server: https://kubernetes.default.svc
    namespace: multi-source-namespace
