apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-example-app
spec:
  project: default
  source:
    repoURL: https://github.com/myorg/myrepo
    path: examples/helm/input
    helm:
      parameters:
      - name: image.tag
        value: "1.21"
      - name: replicaCount
        value: "2"
  destination:
    server: https://kubernetes.default.svc
    namespace: helm-namespace
