# Generated 4 manifests from 2 sources (4 after deduplication)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: helm-online-kustomize-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: 1.29.1
    helm.sh/chart: nginx-0.1.6
  name: helm-online-kustomize-app-nginx
  namespace: helm-online-kustomize
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: helm-online-kustomize-app
      app.kubernetes.io/name: nginx
  template:
    metadata:
      annotations: null
      labels:
        app.kubernetes.io/instance: helm-online-kustomize-app
        app.kubernetes.io/name: nginx
    spec:
      containers:
      - image: docker.io/nginx:1.21
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 5
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 5
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101
        volumeMounts:
        - mountPath: /tmp
          name: emptydir
          subPath: tmp-dir
        - mountPath: /run
          name: emptydir
          subPath: run-dir
        - mountPath: /var/cache/nginx/client_temp
          name: emptydir
          subPath: client-temp-dir
        - mountPath: /var/cache/nginx/proxy_temp
          name: emptydir
          subPath: proxy-temp-dir
        - mountPath: /var/cache/nginx/fastcgi_temp
          name: emptydir
          subPath: fastcgi-temp-dir
        - mountPath: /var/cache/nginx/uwsgi_temp
          name: emptydir
          subPath: uwsgi-temp-dir
        - mountPath: /var/cache/nginx/scgi_temp
          name: emptydir
          subPath: scgi-temp-dir
      securityContext:
        fsGroup: 101
      serviceAccountName: helm-online-kustomize-app-nginx
      volumes:
      - emptyDir: {}
        name: emptydir
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: helm-online-kustomize-app
    environment: local
    team: platform
  name: local-my-app
  namespace: local-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      environment: local
      team: platform
  template:
    metadata:
      labels:
        app: my-app
        environment: local
        team: platform
    spec:
      containers:
      - image: nginx:1.21
        name: my-app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: helm-online-kustomize-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: 1.29.1
    helm.sh/chart: nginx-0.1.6
  name: helm-online-kustomize-app-nginx
  namespace: helm-online-kustomize
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: helm-online-kustomize-app
    app.kubernetes.io/name: nginx
  type: ClusterIP
---
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: helm-online-kustomize-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: 1.29.1
    helm.sh/chart: nginx-0.1.6
  name: helm-online-kustomize-app-nginx
  namespace: helm-online-kustomize
